services:
  jobmanager:
    container_name: pfjobmanager
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - /local/mount/folder:/home/pyflink
    ports:
      - "8085:8081"
    command: jobmanager
    networks:
      - svNetwork
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        jobmanager.memory.process.size: 6gb
        jobmanager.memory.jvm-metaspace.size: 1gb
  taskmanager:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - /local/mount/folder:/home/pyflink
    depends_on:
      - jobmanager
    command: taskmanager
    networks:
      - svNetwork
    scale: 5
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 1
        taskmanager.memory.process.size: 6gb
        taskmanager.memory.jvm-metaspace.size: 1gb
        taskmanager.memory.framework.off-heap.size: 2gb
  kafka:
    image: apache/kafka:3.9.1
    container_name: kafka
    networks:
      - svNetwork
    environment:
        KAFKA_KRAFT_MODE: "true"
        KAFKA_PROCESS_ROLES: broker,controller
        KAFKA_NODE_ID: 1
        KAFKA_NUM_PARTITIONS: 1
        KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1  # Required for single node cluster

        # Listener to use for broker-to-broker communication
        KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
        KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

        KAFKA_LISTENERS: CONTROLLER://localhost:9091,HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093
        KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,DOCKER://kafka:9093
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,HOST:PLAINTEXT
        KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9091
    ports:
      - "9092:9092"
      - "9093:9093"

networks:
  svNetwork:
    name: svNetwork
